config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  root 'users#index'
  resources :users
  resources :places
  resources :categorys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
	has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy] 

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
    
      redirect_to categorys_path
    else
      render 'new'
    end
  end 

  def index
    @categorys = Category.all
  end
 
  def destroy
    @category.destroy

    redirect_to categorys_path
  end

  def update

    if @category.update(category_params)
      redirect_to category_path
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:title) 
  end 

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :find_place, only: [:show, :edit, :update, :destroy] 

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
    
      redirect_to places_path
    else
      render 'new'
    end
  end 

  def index
    @places = Place.all
  end
 
  def destroy
    @place.destroy

    redirect_to places_path
  end

  def update

    if @place.update(place_params)
      redirect_to place_path
    else
      render :edit
    end
  end

  private

  def place_params
    params.require(:place).permit(:title, :category, :description, :agreement, :picture) 
  end 

  def find_place
    @place = Place.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  #     if user_signed_in?
  # 	redirect_to users_path 
  # else
  #   redirect_to places_path
  # end
  end
  def show
  	@users = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar fixed-top navbar-dark bg-success navbar-expand-md ">
        <div class="container">
            <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              &#x2630;
            </button>

            <%= link_to 'Cafe Critic', root_path, class: 'navbar-brand' %>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
                <div class="navbar-nav ml-auto">
                  <div class="navbar-nav ml-auto">
                      <% if user_signed_in? %>
                        <div class="nav-item">
                          <span class="navbar-text">
                            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
                          <span>
                        </div>
                      <% else %>
                          <div class="nav-item">
                             <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                          </div>
                          <div class="nav-item">
                             <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                          </div>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<div class="d-flex justify-content-center align-items-center">
  <%= form_with model:@place, local: true do |f| %>

    <div class="form-row">
      <div class="form-group col-md-12">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <%= f.label :category %>
        <%= f.collection_select :category_id, Category.all, :id, :title %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <%= f.label :picture %>
        <%= f.file_field :picture %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <%= f.label :agreement %>
        <%= f.check_box :agreement %>
      </div>
    </div>
    
  	<div>
    	<%= f.submit %>
  	</div>
  <% end %>    
</div>

app/views/places/edit.html.erb
<h1>Edit place</h1>

<%= render 'form' %>

app/views/places/index.html.erb
<nav class="navbar fixed-top navbar-dark bg-success navbar-expand-md ">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          &#x2630;
        </button>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="navbar-nav ml-auto">
              <div class="navbar-nav ml-auto">
                  <% if user_signed_in? %>
                    <div class="nav-item">
                      <span class="navbar-text">
                        Hello, &nbsp;
                      <span>
                    </div>

                    <div class="dropdown show">
                      <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                      </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</nav> 

<div class="d-flex justify-content-center align-items-center">
  <div class="row">
    <div class="col-sm-12">
      <h2 class="mb-4 mt-4">All places</h2>
    </div>
    <div class="col-sm-12">
      <h2 class="mb-4 mt-4">Select category: All 
        <%# @categorys.each do |category| %>
          <%#= link_to category.title, category_path(category.id) %>
        <%# end %>
      </h2>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center align-items-center">
  <div class="row">
    <% @places.each do |place| %>
    <div class="col-sm-6">
      <div class="card" style="width: 10rem;">
        <% if place.picture.attached? %>
          <%= image_tag place.picture, size: 250,  class: "img-thumbnail" %>
        <% end %>
        <div class="card-body">
          <p class="card-text"><%= link_to place.title, place_path(place.id) %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<%= link_to "Add new place", new_place_path, class: 'btn btn-secondary' %>

app/views/places/new.html.erb
<h1>Add new place</h1>

<%= render 'form' %>

app/views/places/show.html.erb
<div class="d-flex justify-content-center align-items-center">
	<div class="row">
		<div class="col-md-6">
			<h1><%= @place.title %></h1>
			<p><%= @place.description %></p>

		</div>
		<div class="col-md-6">
			<% if @place.picture.attached? %>
	          <%= image_tag @place.picture, size: 250,  class: "img-thumbnail" %>
	        <% end %>
		</div>
	<%= link_to 'Back', places_path %>
	</div>
</div>


  

app/views/users/index.html.erb
<nav class="navbar fixed-top navbar-dark bg-success navbar-expand-md ">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          &#x2630;
        </button>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="navbar-nav ml-auto">
              <div class="navbar-nav ml-auto">
                  <% if user_signed_in? %>
                    <div class="nav-item">
                      <span class="navbar-text">
                        Hello, &nbsp;
                      <span>
                    </div>

                    <div class="dropdown show">
                      <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                      </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</nav> 

<div class="d-flex justify-content-center align-items-center">
  <div class="row">
    <div class="col-sm-12">
      <h2 class="mb-4 mt-4">All places</h2>
    </div>
    <div class="col-sm-12">
      <h2 class="mb-4 mt-4">Select category: All 
      </h2>
    </div>
  </div>
</div>

<%= link_to "Add new place", new_place_path, class: 'btn btn-secondary' %>